# Form implementation generated from reading ui file 'GRAMATICA.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 650)
        MainWindow.setMinimumSize(QtCore.QSize(961, 602))
        MainWindow.setMaximumSize(QtCore.QSize(961, 602))



        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
        " background-color: #1f232a;\n"
        "}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
     

        self.widget_contenido = QtWidgets.QWidget(parent=self.centralwidget)

        self.widget_contenido.setGeometry(QtCore.QRect(0, 0, 961, 602))
        self.widget_contenido.setStyleSheet("QWidget{\n"
        "background-color: rgb(39, 67, 101);\n"
        "}\n"
        "")

      

      

        self.widget_contenido.setObjectName("widget_contenido")
        self.widget_encabezado = QtWidgets.QWidget(parent=self.widget_contenido)
        self.widget_encabezado.setGeometry(QtCore.QRect(410, 0, 150, 80))

        self.widget_encabezado.setObjectName("widget_encabezado")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_encabezado)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label_user = QtWidgets.QLabel(parent=self.widget_encabezado)
        self.label_user.setObjectName("label_user")
        self.horizontalLayout.addWidget(self.label_user)
        self.label_user.setStyleSheet("color: white; font-size: 19px; font-weight: bold;")

        self.stackedWidget_conteni = QtWidgets.QStackedWidget(parent=self.widget_contenido)
        self.stackedWidget_conteni.setGeometry(QtCore.QRect(400, 280, 541, 251))
        self.stackedWidget_conteni.setStyleSheet("background-color: rgb(157, 255, 165);")
        self.stackedWidget_conteni.setObjectName("stackedWidget_conteni")


        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.scroll_area = QtWidgets.QScrollArea(self.page_home)
        self.scroll_area.setGeometry(QtCore.QRect(0, 0, 541, 251)) 
        self.scroll_area.setWidgetResizable(True) 
        self.scroll_area.setObjectName("scroll_area")


        self.label_home = QtWidgets.QLabel()
        self.label_home.setObjectName("label_home")
        self.label_home.setStyleSheet("""
            background-color: rgb(39, 67, 101);
            color: white;
            font-size: 20px;
            padding-left: 6px;
            
        """)

        self.label_home.setWordWrap(True)
        self.scroll_area.setWidget(self.label_home)
        self.stackedWidget_conteni.addWidget(self.page_home)




        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.page_login.setStyleSheet("""
            background-color: rgb(39, 67, 101);
        """)
        


      
        self.tableWidget = QtWidgets.QTableWidget(self.page_login)
        self.tableWidget.setGeometry(QtCore.QRect(1, 0, 535, 251))
        self.tableWidget.setObjectName("tableWidget")
        
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setHorizontalHeaderLabels(["Producciones", "Derivaciones"])
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.setColumnWidth(0, 266)
        self.tableWidget.setColumnWidth(1, 266)

        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Fixed)
        self.tableWidget.horizontalHeader().setSectionsClickable(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)

        
        
        
        self.tableWidget.setStyleSheet("""
         QTableWidget {
             background-color: rgb(39, 67, 101);
             color: white; 
             }
                                       
         QHeaderView::section {
             background-color: rgb(105, 130, 160 );
            color: white;
            font-weight: bold;
         }
        """)
        self.stackedWidget_conteni.addWidget(self.page_login)
        

        lineEdit_stile = """
            QLineEdit {
            background-color:transparent;
            border: 1px solid white;   
            border-radius: 5px;    
            padding-bottom: 1px;        
            font-size: 14px;       
            color: white;            
        }
       """
        
        QPushButton_stile = """
           QPushButton {
             background-color: rgb(105, 130, 160 );  
                             
              border-radius: 5px;                         
                 font-size: 15px; 
                 color: white                            
            }
            QPushButton:hover {
             background-color: white;        
             color: black;             
             }
         )"""


        
        self.widget = QtWidgets.QWidget(parent=self.widget_contenido)
        self.widget.setGeometry(QtCore.QRect(10, 60, 951, 201))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")

        self.labe_Terminal = QtWidgets.QLabel(parent=self.widget)
        self.labe_Terminal.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.labe_Terminal.setStyleSheet("color: rgb(255, 255, 255);")
        self.labe_Terminal.setObjectName("labe_Terminal")
        
        self.lineEdit_Terminal = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_Terminal.setGeometry(QtCore.QRect(10, 60, 341, 21))
        self.lineEdit_Terminal.setObjectName("lineEdit_Terminal")
        self.lineEdit_Terminal.setPlaceholderText("a,b")
        self.lineEdit_Terminal.setStyleSheet(lineEdit_stile)


        self.lab_note = QtWidgets.QLabel(parent=self.widget)
        self.lab_note.setGeometry(QtCore.QRect(370, 20, 101, 31))
        self.lab_note.setStyleSheet("color: rgb(255, 255, 255);")
        self.lab_note.setObjectName("lab_note")
        self.lab_axiom = QtWidgets.QLabel(parent=self.widget)
        self.lab_axiom.setGeometry(QtCore.QRect(730, 20, 101, 31))
        self.lab_axiom.setStyleSheet("color: rgb(255, 255, 255);")
        self.lab_axiom.setObjectName("lab_axiom")

        self.lineEdit_noterminal_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_noterminal_2.setGeometry(QtCore.QRect(730, 60, 191, 21))
        self.lineEdit_noterminal_2.setObjectName("lineEdit_noterminal_2")
        self.lineEdit_noterminal_2.setPlaceholderText("S")
        self.lineEdit_noterminal_2.setStyleSheet(lineEdit_stile)

        self.lab_produ = QtWidgets.QLabel(parent=self.widget)
        self.lab_produ.setGeometry(QtCore.QRect(10, 90, 101, 21))
        self.lab_produ.setStyleSheet("color: rgb(255, 255, 255);")
        self.lab_produ.setObjectName("lab_produ")

        self.lineEdit_produ = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_produ.setGeometry(QtCore.QRect(10, 120, 911, 21))
        self.lineEdit_produ.setObjectName("lineEdit_produ")
        self.lineEdit_produ.setStyleSheet(lineEdit_stile)
        self.lineEdit_produ.setPlaceholderText("S,aA;A,aA;A,b")

        self.pushButton_generate_gra = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_generate_gra.setGeometry(QtCore.QRect(700, 160, 221, 31))
        self.pushButton_generate_gra.setStyleSheet("font-size: 15px")
        self.pushButton_generate_gra.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_generate_gra.setObjectName("pushButton_generate_gra")
        self.pushButton_generate_gra.setStyleSheet(QPushButton_stile)

        self.lineEdit_nterminal_ = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_nterminal_.setGeometry(QtCore.QRect(370, 60, 331, 21))
        self.lineEdit_nterminal_.setObjectName("lineEdit_nterminal_")
        self.lineEdit_nterminal_.setPlaceholderText("S,A")
        self.lineEdit_nterminal_.setStyleSheet(lineEdit_stile)

        self.widget_2 = QtWidgets.QWidget(parent=self.widget_contenido)
        self.widget_2.setGeometry(QtCore.QRect(10, 260, 381, 321))
        self.widget_2.setObjectName("widget_2")
        self.labe_Terminal_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.labe_Terminal_2.setGeometry(QtCore.QRect(10, 20, 281, 31))
        self.labe_Terminal_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.labe_Terminal_2.setObjectName("labe_Terminal_2")

        self.lineEdit_Terminal_3 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_Terminal_3.setGeometry(QtCore.QRect(10, 60, 371, 21))
        self.lineEdit_Terminal_3.setObjectName("lineEdit_Terminal_3")
        self.lineEdit_Terminal_3.setPlaceholderText("aab")
        self.lineEdit_Terminal_3.setStyleSheet(lineEdit_stile)

        self.pushButton_validate_W = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_validate_W.setGeometry(QtCore.QRect(80, 110, 221, 31))
        self.pushButton_validate_W.setStyleSheet("font-size: 15px")
        self.pushButton_validate_W.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_validate_W.setObjectName("pushButton_validate_W")
        self.pushButton_validate_W.setStyleSheet(QPushButton_stile)

        self.labe_Terminal_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.labe_Terminal_4.setGeometry(QtCore.QRect(10, 150, 361, 141))
        self.labe_Terminal_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
       
       


        font = QtGui.QFont()
        font.setPointSize(20)
        self.labe_Terminal_4.setFont(font)
        self.labe_Terminal_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.labe_Terminal_4.setObjectName("labe_Terminal_4")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget_contenido)
        self.widget_3.setGeometry(QtCore.QRect(390, 540, 561, 61))
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")

        self.pushButton_generate_gra_2 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_generate_gra_2.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.pushButton_generate_gra_2.setStyleSheet("font-size: 15px")
        self.pushButton_generate_gra_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_generate_gra_2.setObjectName("pushButton_generate_gra_2")
        self.pushButton_generate_gra_2.setStyleSheet(QPushButton_stile)

        self.pushButton_deriva = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_deriva.setGeometry(QtCore.QRect(190, 20, 161, 31))
        self.pushButton_deriva.setStyleSheet("font-size: 15px")
        self.pushButton_deriva.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_deriva.setObjectName("pushButton_deriva")
        self.pushButton_deriva.setStyleSheet(QPushButton_stile)

        self.pushButton_deriva_2 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_deriva_2.setGeometry(QtCore.QRect(440, 20, 91, 31))
        self.pushButton_deriva_2.setStyleSheet("font-size: 15px")
        self.pushButton_deriva_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_deriva_2.setObjectName("pushButton_deriva_2")
        self.pushButton_deriva_2.setStyleSheet(QPushButton_stile)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_conteni.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.pushButton_generate_gra_2.clicked.connect(lambda: self.change_page(self.stackedWidget_conteni.indexOf(self.page_home)))
        self.pushButton_deriva.clicked.connect(lambda: self.change_page(self.stackedWidget_conteni.indexOf(self.page_login)))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GRAMATICA"))
        self.label_user.setText(_translate("MainWindow", "GRAMATICA"))
        self.label_home.setText(_translate("MainWindow", ""))
       

 
        self.labe_Terminal.setText(_translate("MainWindow", "Terminales  T"))
        self.lab_note.setText(_translate("MainWindow", "No Terminales  N"))
        self.lab_axiom.setText(_translate("MainWindow", "Axioma S"))
        self.lab_produ.setText(_translate("MainWindow", "Producciones"))
        self.pushButton_generate_gra.setText(_translate("MainWindow", "Guardar gramatica"))
        self.labe_Terminal_2.setText(_translate("MainWindow", "Insertar Palabra "))
        self.pushButton_validate_W.setText(_translate("MainWindow", "Validar Palabra"))
        self.labe_Terminal_4.setText(_translate("MainWindow", ""))
        self.pushButton_generate_gra_2.setText(_translate("MainWindow", "Gramatica"))
        self.pushButton_deriva.setText(_translate("MainWindow", "Derivacion"))
        self.pushButton_deriva_2.setText(_translate("MainWindow", "Reiniciar"))

    def change_page(self, index):
     self.stackedWidget_conteni.setCurrentIndex(index)
     print(f"Página actual: {index}")
    



